# Generated by Django 3.2.15 on 2022-08-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.CharField(max_length=256),
        ),
    ]
