# Generated by Django 3.2.15 on 2022-08-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApi', '0004_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
